apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      affinity:           #for master and slave to run on different nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: redis-master
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-slave
        image: redis:6.0
        ports:
        - containerPort: 6379
        command: ["redis-server", "--replicaof", "redis-master.redis.svc.cluster.local", "6379"]
